#-------------------------------
# Site Settings
title: Walter Julio Nicholls
description: Professor, Department Chair
color_scheme: light # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image:  # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Updates'
      url: '/updates'
    - title: 'Research'
      url: '/research/'
    - title: 'Books'
      url: '/books/'
    - title: 'Publications'
      url: '/publications/'
      sub_items:
      - title: "Guest Editorships"
        url: "/publications/#guest-editorships"
      - title: "Articles"
        url: "/publications/#articles"
      - title: "Papers Under Review"
        url: "/publications/#papers-under-review"
      - title: "Book Chapters"
        url: "/publications/#book-chapters"
      - title: "Commentaries and Encyclopedia Entries"
        url: "/publications/#commentaries-and-encyclopedia-entries"
    - title: 'Public Talks'
      url: '/public-talks/'
    - title: 'My Gallery'
      url: '/my-gallery/'

#-------------------------------
# Author Settings
author:
  author_name: Walter Julio Nicholls
  author_role: Professor, Department Chair
  author_bio: Urban Planning and Public Policy, PhD Urban Planning, University of California, Los Angeles, 218C Social Ecology 1
  author_avatar: '/images/profile.jpg'
  cta_button_text: Contact Me
  cta_button_link: '/contact/'



#-------------------------------
research:
  enable: true
  research_title: "My Research"
  research_description: 

updates:
  enable: true
  updates_title: "Latest Updates"
  updates_page_url: "/updates"
  updates_description: "Stay informed with the latest events and announcements. Check back monthly for updates."

updates-item:
  - year: 2024
    events:
      - date: "2 FEB"
        content: "Add Announcement here."
      - date: "3 FEB"
        content: "Add Announcement here."
      - date: "2 SEPT"
        content: "Add Announcement here."
      - date: 
        content: "Add Announcement here."
      - date: 
        content: "Add Announcement here."

images:
  images_title: "My Gallery"
  images_description: "Explore a collection of images that reflect the breadth and depth of my work, from engaging with students in the classroom to conducting field research in diverse urban settings."

publication:
  enable: true
  publication_title: "Books" # Change or leave it empty if you want the title to be set elsewhere
  publication_description: 
  publication_page_url:  # The URL where all publications are listed
  publication_image_url: "/images/books.jpg" # The image URL for the book or publication
  publication_author:  # The name of the author
  publication_content: "This book traces the immigrant rights movement in the U.S., from its grassroots beginnings in the 1990s to its national prominence, especially during the 2016 election. Initially united around calls for comprehensive immigration reform, activists sought legal recognition for immigrants based on their ties to American values. Despite significant progress during the Obama era, the movement faced internal divisions and challenges in confronting mainstream narratives, ultimately becoming entangled within the system it aimed to change. <a href=\"https://www.amazon.com/Immigrant-Rights-Movement-National-Citizenship/dp/1503609324\"><b>Get it today!</b></a>"


#-------------------------------
# about settings
about_settings:
  enable: true
  about_title: "About Walter"
  about_description: "I am Dr. Walter Nicholls, Associate Professor of Urban Planning and Public Policy at the University of California, Irvine. My research centers on the role of cities in social movements and how immigrants develop political agency in hostile environments. I teach courses in urban sociology, immigration studies, and qualitative methods, with a focus on understanding the dynamics of cities, social change, and immigrant rights. My work seeks to inspire both academic inquiry and real-world action on these critical issues."


#-------------------------------
# Videos Settings
videos_settings:
  enable: true
  videos_title: Public Talks
  videos_description:



articles:
  enable: true
  articles_title: "Latest Publication"
  articles_description: "Explore my latest publications on a variety of topics."


#-------------------------------
# Social Icons Settings
social:
# - {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://www.facebook.com/profile.php?id=100090929704323"}
# - {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/PenelopeAnthias"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/walternicholls/"}
# - {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://tiktok.com"}
# - {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@penelopeanthias"}
# - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# - {icon: "fa-brands fa-microsoft", name: "Microsoft", link: "https://microsoft.com"}
# - {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}
- {icon: "fa-solid fa-envelope", name: "Email", link: "mailto:wnicholl@uci.edu"}
- {icon: "fa-solid fa-globe", name: "Website", link: "https://faculty.sites.uci.edu/nicholls/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: mjkbdaor # Add your form_id
  description: Thank you for visiting my website. If you would like to discuss research collaborations, PhD supervision, or have inquiries about my work on Indigenous land rights, resource politics, or other related topics, please feel free to get in touch by filling out the form below. I look forward to connecting with you.

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
